# https://medium.com/@shakyShane/laravel-docker-part-1-setup-for-development-e3daaefaf3c?token=i6JtSuvpAr7sbCvu
version: '2'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
    ports:
        - 8080:8080
        - 8001:8001
        - 3001:3001

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8000:80

  # The Database
  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
      - /app/node_modules
    environment:
      - "MYSQL_DATABASE=tbrasil_site"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "33061:3306"
volumes:
  dbdata: