# https://medium.com/@shakyShane/laravel-docker-part-1-setup-for-development-e3daaefaf3c?token=i6JtSuvpAr7sbCvu
version: '2'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    env_file:
      - .env
    environment:
      - "DB_PORT=${DB_PORT}"
      - "BASE_URL=${BASE_URL}"
      - "DB_HOST=${MYSQL_HOST}"
      - "APP_DEBUG=${MYSQL_HOST}"
      - "APP_URL=${APP_URL}"
      - "SECURITY_SALT=${SECURITY_SALT}"
      - "MYSQL_HOST=${MYSQL_HOST}"
      - "MYSQL_USERNAME=${MYSQL_USERNAME}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MAIL_DRIVER=${MAIL_DRIVER}"
      - "MAIL_HOST=${MAIL_HOST}"
      - "MAIL_USERNAME=${MAIL_USERNAME}"
      - "MAIL_PASSWORD=${MAIL_PASSWORD}"   
      - "MYSQL_ATTR_SSL_CA=${MYSQL_ATTR_SSL_CA}"
      - "GOOGLE_RECAPTCHA_KEY=${GOOGLE_RECAPTCHA_KEY}"
      - "GOOGLE_RECAPTCHA_SECRET=${GOOGLE_RECAPTCHA_SECRET}"
      - "MONTHLY_PRICE=${MONTHLY_PRICE}"
      - "YEARLY_PRICE=${YEARLY_PRICE}"      
    ports:
        - 8080:8080
        - 8001:8001
        - 3001:3001

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 80:80

  # The Database
  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
      - /app/node_modules
    environment:
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
    ports:
        - "33061:3306"
volumes:
  dbdata: